14 èþë 2015 16:25:19.661 [ERROR] - Connection to MySQL DB not created
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.workfusion.project.dao.connection.MySqlConnectionManager.createConnection(MySqlConnectionManager.java:43)
	at com.workfusion.project.dao.connection.MySqlConnectionManager.<init>(MySqlConnectionManager.java:29)
	at com.workfusion.project.dao.connection.MySqlConnectionManager.<init>(MySqlConnectionManager.java:22)
	at com.workfusion.project.dao.connection.MySqlConnectionManager$Holder.<clinit>(MySqlConnectionManager.java:33)
	at com.workfusion.project.dao.connection.MySqlConnectionManager.getInstance(MySqlConnectionManager.java:37)
	at com.workfusion.project.dao.impl.ValueDAOImpl.<init>(ValueDAOImpl.java:22)
	at com.workfusion.project.dao.impl.ValueDAOImpl.<init>(ValueDAOImpl.java:27)
	at com.workfusion.project.dao.impl.ValueDAOImpl$Holder.<clinit>(ValueDAOImpl.java:31)
	at com.workfusion.project.dao.impl.ValueDAOImpl.getInstance(ValueDAOImpl.java:35)
	at com.workfusion.project.main.Main.main(Main.java:17)
14 èþë 2015 17:02:37.949 [ERROR] - com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
